name: Verademo

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean verify

  sast-scan:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get the Java API wrapper
      uses: wei/curl@master
      with:
        args: -sS -o VeracodeJavaAPI.jar "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/19.6.5.8/vosp-api-wrappers-java-19.6.5.8.jar"

    - name: Start SAST scan
      run: java -jar VeracodeJavaAPI.jar
      -action uploadandscan
      -vid ${{secrets.VERACODE_API_ID}}
      -vkey ${secrets.VERACODE_API_SECRET}}
      -appname VeraDemo
      -createprofile false
      -scantimeout 30
      -version "GitHub Actions job $GITHUB_RUN_NUMBER"
      -filepath target/verademo.war
